plugins:
    hpc:
        # Could be 'central_deployment_agent' or 'host_agent'.
        # If 'central_deployment_agent', this plugin will be executed on the
        # deployment dedicated agent, other wise it will be executed on the host agent.
        executor: central_deployment_agent

        # URL to archive containing the plugin or name of directory containing
        # the plugin if it is included in the the blueprint directory under the
        # "plugins" directory.
        source: https://github.com/MSO4SC/cloudify-hpc-plugin/archive/canary.zip
        package_name: cloudify-hpc-plugin
        package_version: '1.2'

workflows:
    run_jobs:
        mapping: hpc.hpc_plugin.workflows.run_jobs

node_types:
    hpc.nodes.Compute:
        derived_from: cloudify.nodes.Compute
        properties:
            config:
                description: credentials, timezone and workload manager
            external_monitor_entrypoint:
                description: Monitor entrypoint, port and orchestrator port
                default: ""
                type: string
            external_monitor_port:
                description: Monitor entrypoint, port and orchestrator port
                default: ":9090"
                type: string
            external_monitor_type:
                description: Monitor type, e.g PROMETHEUS
                default: "PROMETHEUS"
                type: string
            external_monitor_orchestrator_port:
                description: Monitor entrypoint, port and orchestrator port
                default: ":8079"
                type: string
            job_prefix:
                description: Job name prefix for this HPC
                default: "cfyhpc"
                type: string
            base_dir:
                description: Root directory of all executions
                default: "$HOME"
                type: string
            workdir_prefix:
                description: Prefix of the working directory instead of blueprint name
                default: ""
                type: string
            simulate:
                description: Set to true to simulate job without sending it
                type: boolean
                default: False
            skip_cleanup:
                description: True to not clean all files at deployment removal
                type: boolean
                default: False
            agent_config:
                default:
                    install_method: none
        interfaces:
            cloudify.interfaces.lifecycle:
                start:
                    implementation: hpc.hpc_plugin.tasks.prepare_hpc
                    inputs:
                        config:
                            default: { get_property: [SELF, config] }
                        base_dir:
                            default: { get_property: [SELF, base_dir] }
                        workdir_prefix:
                            default: { get_property: [SELF, workdir_prefix] }
                        simulate:
                            default: { get_property: [SELF, simulate] }
                stop:
                    implementation: hpc.hpc_plugin.tasks.cleanup_hpc
                    inputs:
                        config:
                            default: { get_property: [SELF, config] }
                        skip:
                            default: { get_property: [SELF, skip_cleanup] }
                        simulate:
                            default: { get_property: [SELF, simulate] }
            cloudify.interfaces.monitoring:
                start:
                    implementation: hpc.hpc_plugin.tasks.start_monitoring_hpc
                    inputs:
                        config:
                            default: { get_property: [SELF, config] }
                        external_monitor_entrypoint: 
                            default: { get_property: [SELF, external_monitor_entrypoint] }
                        external_monitor_port: 
                            default: { get_property: [SELF, external_monitor_port] }
                        external_monitor_orchestrator_port: 
                            default: { get_property: [SELF, external_monitor_orchestrator_port] }
                        simulate:
                            default: { get_property: [SELF, simulate] }
                stop:
                    implementation: hpc.hpc_plugin.tasks.stop_monitoring_hpc
                    inputs:
                        config:
                            default: { get_property: [SELF, config] }
                        external_monitor_entrypoint: 
                            default: { get_property: [SELF, external_monitor_entrypoint] }
                        external_monitor_port: 
                            default: { get_property: [SELF, external_monitor_port] }
                        external_monitor_orchestrator_port: 
                            default: { get_property: [SELF, external_monitor_orchestrator_port] }
                        simulate:
                            default: { get_property: [SELF, simulate] }

    hpc.nodes.job:
        derived_from: cloudify.nodes.Root
        properties:
            deployment:
                description: Deployment script and inputs
                default: {}
            job_options:
                description: Job main command and options
            skip_cleanup:
                description: True to not clean after execution (debug purposes)
                type: boolean
                default: False
        interfaces:
            cloudify.interfaces.lifecycle:
                start: # needs to be start to have the hpc credentials
                    implementation: hpc.hpc_plugin.tasks.bootstrap_job
                    inputs:
                        deployment:
                            description: Deployment scripts and inputs
                            default: { get_property: [SELF, deployment] }
                        skip_cleanup:
                            default: { get_property: [SELF, skip_cleanup] }
                stop:
                    implementation: hpc.hpc_plugin.tasks.revert_job
                    inputs:
                        deployment:
                            description: Undeployment script and inputs
                            default: { get_property: [SELF, deployment] }
                        skip_cleanup:
                            default: { get_property: [SELF, skip_cleanup] }
            hpc.interfaces.lifecycle:
                queue:
                    implementation: hpc.hpc_plugin.tasks.send_job
                    inputs:
                        job_options:
                            default: { get_property: [SELF, job_options] }
                cleanup:
                    implementation: hpc.hpc_plugin.tasks.cleanup_job
                    inputs:
                        job_options:
                            default: { get_property: [SELF, job_options] }
                        skip:
                            default: { get_property: [SELF, skip_cleanup] }
                cancel:
                    implementation: hpc.hpc_plugin.tasks.stop_job
                    inputs:
                        job_options:
                            default: { get_property: [SELF, job_options] }
    
    hpc.nodes.singularity_job:
        derived_from: hpc.nodes.job

relationships:
    job_contained_in_hpc:
        derived_from: cloudify.relationships.contained_in
        source_interfaces:
            cloudify.interfaces.relationship_lifecycle:
                preconfigure:
                    implementation: hpc.hpc_plugin.tasks.preconfigure_job
                    inputs:
                        config: 
                            default: { get_property: [TARGET, config] }
                        external_monitor_entrypoint: 
                            default: { get_property: [TARGET, external_monitor_entrypoint] }
                        external_monitor_port: 
                            default: { get_property: [TARGET, external_monitor_port] }
                        external_monitor_type: 
                            default: { get_property: [TARGET, external_monitor_type] }
                        external_monitor_orchestrator_port: 
                            default: { get_property: [TARGET, external_monitor_orchestrator_port] }
                        job_prefix: 
                            default: { get_property: [TARGET, job_prefix] }
                        simulate:
                            default: { get_property: [TARGET, simulate] }

    job_depends_on:
        derived_from: cloudify.relationships.depends_on
