plugins:
  hpc:
    # Could be 'central_deployment_agent' or 'host_agent'.
    # If 'central_deployment_agent', this plugin will be executed on the
    # deployment dedicated agent, other wise it will be executed on the host agent.
    executor: central_deployment_agent

    # URL to archive containing the plugin or name of directory containing
    # the plugin if it is included in the the blueprint directory under the
    # "plugins" directory.
    source: https://github.com/MSO4SC/cloudify-hpc-plugin/archive/master.zip
    package_name: cloudify-hpc-plugin
    package_version: '0.1'

workflows:
    run_jobs:
        mapping: hpc.hpc_plugin.workflows.run_jobs
        parameters:
            monitor_config:
                description: Monitor system configuration
                default:
                    host: '[HOST]'
                    user: '[USER]'
                    passwd: '[PASSWD]'
            jobname_prefix:
                description: Prefix to attach to job names in the HPC
                default: 'cfy'
                type: string
            simulate:
                description: True to simulate the monitoring connection
                default: False
            

node_types:
    hpc.nodes.Compute:
        derived_from: cloudify.nodes.Compute
        properties:
            config:
                description: credentials, timezone and workload manager
            simulate:
                description: Set to true to simulate job without sending it
                type: boolean
                default: false
            agent_config:
                default:
                    install_method: none
        interfaces:
            cloudify.interfaces.lifecycle:
                start:
                    implementation: hpc.hpc_plugin.tasks.login_connection
                    inputs:
                        credentials:
                            default: { get_property: [SELF, config, credentials] }
                        simulate:
                            default: { get_property: [SELF, simulate] }
            cloudify.interfaces.monitoring:
                start:
                    implementation: hpc.hpc_plugin.tasks.monitor_hpc
                    inputs:
                        credentials:
                            default: { get_property: [SELF, config, credentials] }
                        workload_manager:
                            default: { get_property: [SELF, config, workload_manager] }
                        country_tz:
                            default: { get_property: [SELF, config, country_tz] }
                        simulate:
                            default: { get_property: [SELF, simulate] }

    hpc.nodes.job:
        derived_from: cloudify.nodes.Root
        properties:
            deployment:
                description: Deployment script and inputs
                default: {}
            job_options:
                description: Job main command and options
        interfaces:
            cloudify.interfaces.lifecycle:
                start:
                    implementation: hpc.hpc_plugin.tasks.deploy_job
                    inputs:
                        deployment:
                            description: Deployment script and inputs
                            default: { get_property: [SELF, deployment] }
            hpc.interfaces.lifecycle:
                queue:
                    implementation: hpc.hpc_plugin.tasks.send_job
                    inputs:
                        job_options:
                            default: { get_property: [SELF, job_options] }

relationships:
    job_contained_in_hpc:
        derived_from: cloudify.relationships.contained_in
        source_interfaces:
            cloudify.interfaces.relationship_lifecycle:
                preconfigure:
                    implementation: hpc.hpc_plugin.tasks.preconfigure_job
                    inputs:
                        credentials: 
                            default: { get_property: [TARGET, config, credentials] }
                        workload_manager:
                            default: { get_property: [TARGET, config, workload_manager] }
                        simulate:
                            default: { get_property: [TARGET, simulate] }

    job_depends_on:
        derived_from: cloudify.relationships.depends_on
